services:
  eleventy-blog:
    image: github.com/feydakinjedi/eleventy-blog.git
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    # command: ["npx", "@11ty/eleventy", "--serve"]
    command: ["npm", "start"]
