services:
  eleventy:
    image: node:18
    container_name: eleventy-blog
    working_dir: /app
    ports:
      - "5175:8080"
    command: sh -c "git clone https://github.com/FeydakinJedi/eleventy-blog.git /app && npm install && npx @11ty/eleventy --serve"
    restart: unless-stopped
